#!/bin/bash

wget -q -O androidstudio.tar.gz https://edgedl.me.gvt1.com/android/studio/ide-zips/2025.3.4.7/android-studio-panda4-patch1-linux.tar.gz
tar -xzf androidstudio.tar.gz -C /opt/
rm androidstudio.tar.gz