#!/bin/bash

for uid in $(grep -E ^[A-Za-z0-9_-]+:x:${user_id}: /etc/passwd | sed -E "s/^([A-Za-z0-9]+):.*$/\1/"); do
	userdel -r $uid
done
for uid in $(grep -E ^[A-Za-z0-9_-]+:x:${group_id}: /etc/group | sed -E "s/^([A-Za-z0-9]+):.*$/\1/"); do
	groupdel -r $uid
done

groupadd --gid ${group_id} ${user_name}
useradd --uid ${user_id} --gid ${group_id} -d /home/${user_name} -s /bin/bash -m ${user_name}

mkdir -p /home/${user_name}

dbus-uuidgen --ensure

chown -R ${user_name}:${user_name} /home/${user_name}
