#!/bin/bash

workingdir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
pushd $workingdir

if command -v yum >/dev/null; then

	yum install -q -y podman podman-compose
	chmod u+s /usr/bin/newuidmap
	chmod u+s /usr/bin/newgidmap

elif command -v apt >/dev/null; then

	apt install -q -y podman podman-compose

fi
chmod u+s /usr/bin/newuidmap
chmod u+s /usr/bin/newgidmap
echo "user.max_user_namespaces=28633" > /etc/sysctl.d/userns.conf
usermod --add-subuids 100000-165535 --add-subgids 100000-165535 ${user_name}

#Not sure why but this fixes newuidmap for podman
if command -v yum >/dev/null; then
	yum reinstall -q -y shadow
elif command -v apt >/dev/null; then
	apt reinstall -q -y shadow
fi

loginctl enable-linger ${user_id}

popd
