#!/bin/bash

# TODO handle yum case

if command -v apt >/dev/null; then

	# TODO determine host capability. Assuming version 580 is available for now
	apt -q update
	apt -q -y install software-properties-common
	add-apt-repository -y ppa:graphics-drivers/ppa
	apt install -q -y nvidia-driver-580

fi
