#!/bin/bash
spawn_point=${1}
spawn_config=${2}
instance_name=${3}
user_name=${4}
user_id=${5}
group_id=${6}

. scripts/.env

pushd scripts >/dev/null
if [ -f spawn_points/${spawn_point}/system_setup ]; then
	spawn_points/${spawn_point}/system_setup $spawn_point $instance_name $user_name $user_id $group_id
fi
popd >/dev/null

for i in $(build_order $spawn_config); do
	if [ -f spawn_configs/${i}/scripts/system_setup ]; then
		spawn_configs/${i}/scripts/system_setup $spawn_point $instance_name $user_name $user_id $group_id
	fi
done