#!/bin/bash

for i in $(cat .build_config); do
	export $i
done

. scripts/.env

pushd scripts >/dev/null
if [ -f spawn_points/${spawn_point}/system_setup ]; then
	echo
	echo "START spawn_points/${spawn_point}/system_setup "
	echo
	spawn_points/${spawn_point}/system_setup 
	echo
	echo "END spawn_points/${spawn_point}/system_setup" 
	echo

fi
popd >/dev/null

for i in $(build_order $spawn_config); do
	if [ -f spawn_configs/${i}/scripts/system_setup ]; then
		echo
		echo "START spawn_configs/${i}/scripts/system_setup "
		echo
		spawn_configs/${i}/scripts/system_setup"
		echo
		echo "END spawn_configs/${i}/scripts/system_setup"
		echo
	fi
done