#!/bin/bash
spawn_config=${1}
spawn_point=${2}

workingdir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd ) > /dev/null
pushd $workingdir > /dev/null

. .env

user_name=$(whoami)
sudo chown -R ${user_name}:${user_name} $HOME

pushd .. > /dev/null
if [ -d scripts/spawn_points/${spawn_point}/home ]; then
	scripts/populate_home scripts/spawn_points/${spawn_point}/home
fi
for i in $(build_order $spawn_config); do
	if [ -d spawn_configs/${i}/home ]; then
		scripts/populate_home spawn_configs/${i}/home
	fi
done
popd > /dev/null

if [ spawn_points/${spawn_point}/user_setup ]; then
	echo
	echo "START spawn_points/${spawn_point}/user_setup $spawn_config"
	echo
	spawn_points/${spawn_point}/user_setup $spawn_config
	echo
	echo "END spawn_points/${spawn_point}/user_setup $spawn_config"
	echo
fi

pushd .. > /dev/null
for i in $(build_order $spawn_config); do
	if [ -f spawn_configs/${i}/scripts/user_setup ]; then
		echo
		echo "START spawn_configs/${i}/scripts/user_setup $spawn_point"
		echo
		spawn_configs/${i}/scripts/user_setup $spawn_point
		echo
		echo "END spawn_configs/${i}/scripts/user_setup $spawn_point"
		echo
	fi
done
popd > /dev/null

popd > /dev/null